const chalk=require('chalk');
console.time('add');
let a=90;
let b=20;
add=a+b;
console.log(add);
console.log(chalk.blue(add));
// console.warn(chalk.yellow(add));
// console.error(chalk.red(add));
console.timeEnd('add');
